---
# tasks file for ec2
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    key_name: "demo"
    vpc_subnet_id: subnet-08122d81b0b77a5fb
    instance_type: "{{type}}"
    security_group: default
    region: us-east-1
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    network:
      assign_public_ip: true
    image_id: ami-0b6c6ebed2801a5cb
    
