---
# tasks file for httpd

- name: Install apache httpd  (state=present is optional)
  apt:
    name: apache2
    state: present

- name: Copy file with owner and permissions
  copy:
    src: files/index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'
